# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      # - '.github/**'
      - ".gitignore"
      - "LICENSE"
      - "README.md"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      # - '.github/**'
      - ".gitignore"
      - "LICENSE"
      - "README.md"
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v --enable-code-coverage

    - name: Test coverage
      uses: ningkaiqiang/spm-lcov-action@master
      with:
          output-file: ./coverage/lcov.info
    
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
